import {
  resolveCollectionIteratee,
  type CollectionIteratee,
} from "../collection/_iterateeHelpers.js";

/**
 * Creates an object with the same values as object and keys generated by running
 * each own enumerable string keyed property of object thru iteratee.
 *
 * @param {Object} object - The object to iterate over.
 * @param {Function} [iteratee] - The function invoked per iteration.
 * @return {Object} Returns the new mapped object.
 *
 * @example
 * mapKeys({ a: 1, b: 2 }, (value, key) => key + value); // { a1: 1, b2: 2 }
 */
export const mapKeys = (
  object: unknown,
  iteratee?: CollectionIteratee,
): Record<string, unknown> => {
  const target = Object(object) as Record<string, unknown>;
  const result: Record<string, unknown> = {};
  const mapper = resolveCollectionIteratee(iteratee);
  const keys = Object.keys(target);

  for (const key of keys) {
    const mappedKey = String(mapper(target[key], key, object));
    result[mappedKey] = target[key];
  }

  return result;
};
