import {
  resolveCollectionIteratee,
  type CollectionIteratee,
} from "../collection/_iterateeHelpers.js";

/**
 * Creates an object with the same keys as object and values generated by running
 * each own enumerable string keyed property of object thru iteratee.
 *
 * @param {Object} object - The object to iterate over.
 * @param {Function} [iteratee] - The function invoked per iteration.
 * @return {Object} Returns the new mapped object.
 *
 * @example
 * mapValues({ a: 1, b: 2 }, value => value * 2); // { a: 2, b: 4 }
 */
export const mapValues = (
  object: unknown,
  iteratee?: CollectionIteratee,
): Record<string, unknown> => {
  const target = Object(object) as Record<string, unknown>;
  const result: Record<string, unknown> = {};
  const mapper = resolveCollectionIteratee(iteratee);
  const keys = Object.keys(target);

  for (const key of keys) {
    result[key] = mapper(target[key], key, object);
  }

  return result;
};
